//! Generated gRPC messages, servers and clients for package `aulo.v1`.
//!
//! This is the only crate that depends on tonic and prost; everything else
//! talks to the API through these types.

/// Package `aulo.v1`, generated by `build.rs` from `proto/aulo/v1`.
pub mod aulo {
    pub mod v1 {
        tonic::include_proto!("aulo.v1");
    }
}

#[cfg(test)]
mod tests {
    use super::aulo::v1::{ConverseRequest, Event, TextDelta, converse_request, event};
    use prost::Message;

    #[test]
    fn event_round_trips() {
        let event = Event {
            kind: Some(event::Kind::TextDelta(TextDelta {
                turn_id: "01J00000000000000000000000".into(),
                text: "hello".into(),
            })),
        };
        let bytes = event.encode_to_vec();
        assert_eq!(Event::decode(bytes.as_slice()).unwrap(), event);
    }

    #[test]
    fn converse_request_round_trips() {
        let request = ConverseRequest {
            submission: Some(converse_request::Submission::UserTurn(
                super::aulo::v1::UserTurn {
                    text: "open the browser".into(),
                },
            )),
        };
        let bytes = request.encode_to_vec();
        assert_eq!(ConverseRequest::decode(bytes.as_slice()).unwrap(), request);
    }
}
